name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: [self-hosted, linux-build]
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            vscode_arch: x64
            archive: tar.gz
            artifact: openvscode-server-linux-x64

    env:
      GITHUB_TOKEN: ${{ github.token }}
      GH_TOKEN: ${{ github.token }}
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
      ELECTRON_SKIP_BINARY_DOWNLOAD: "1"
      npm_config_arch: ${{ matrix.vscode_arch }}
      VSCODE_ARCH: ${{ matrix.vscode_arch }}
      NODE_OPTIONS: --max-old-space-size=8192
      MALLOC_ARENA_MAX: "2"
      CI: "1"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - run: npm ci
      - run: npm ci
        working-directory: remote

      - run: npm run server:init

      - run: |
          npm run gulp compile-build-without-mangling
          npm run gulp extensions-ci
          npm run gulp minify-vscode-reh
          npm run gulp vscode-web-min-ci

      - run: npm run gulp vscode-reh-${{ matrix.platform }}-${{ matrix.vscode_arch }}-min-ci

      - name: Locate output dir
        id: find_out
        run: |
          set -euo pipefail
          name="vscode-reh-${{ matrix.platform }}-${{ matrix.vscode_arch }}"
          for d in "./$name" "../$name" "./.build/$name" "./.build/linux/$name"; do
            if [ -d "$d" ]; then
              echo "out_dir=$d" >> "$GITHUB_OUTPUT"
              exit 0
            fi
          done
          find . -maxdepth 4 -type d -name "vscode-reh-*"
          exit 1

      - run: |
          set -euo pipefail
          src="${{ steps.find_out.outputs.out_dir }}"
          base="${{ matrix.artifact }}"
          tmpdir="$(mktemp -d)"
          cp -R "$src" "$tmpdir/$base"
          tar -czf "${base}.${{ matrix.archive }}" -C "$tmpdir" "$base"

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}.${{ matrix.archive }}
