name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            runs_on: ubuntu-latest
            vscode_arch: x64
            archive: tar.gz
            artifact: openvscode-server-linux-x64
          - platform: darwin
            runs_on: macos-latest
            vscode_arch: arm64
            archive: tar.gz
            artifact: openvscode-server-darwin-arm64
          - platform: win32
            runs_on: windows-latest
            vscode_arch: x64
            archive: zip
            artifact: openvscode-server-win32-x64

    runs-on: ${{ matrix.runs_on }}

    env:
      GITHUB_TOKEN: ${{ github.token }}
      GH_TOKEN: ${{ github.token }}
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
      ELECTRON_SKIP_BINARY_DOWNLOAD: "1"
      npm_config_arch: ${{ matrix.vscode_arch }}
      VSCODE_ARCH: ${{ matrix.vscode_arch }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config dbus xvfb libgtk-3-0 libxkbfile-dev libkrb5-dev libgbm1 rpm libsecret-1-dev jq

      - if: matrix.platform == 'win32'
        run: git config --system core.longpaths true
        shell: pwsh

      - run: npm ci
      - run: npm ci
        working-directory: remote

      - run: npm run server:init

      - if: matrix.platform != 'win32'
        run: |
          npm run gulp vscode-reh-${{ matrix.platform }}-${{ matrix.vscode_arch }}-min
          mv ../vscode-reh-${{ matrix.platform }}-${{ matrix.vscode_arch }} ../vscode-server-${{ matrix.platform }}-${{ matrix.vscode_arch }}
          tar -czf ${{ matrix.artifact }}.${{ matrix.archive }} -C .. vscode-server-${{ matrix.platform }}-${{ matrix.vscode_arch }}

      - if: matrix.platform == 'win32'
        run: |
          npm run gulp vscode-reh-${{ matrix.platform }}-${{ matrix.vscode_arch }}-min
          Move-Item ..\\vscode-reh-${{ matrix.platform }}-${{ matrix.vscode_arch }} ..\\vscode-server-${{ matrix.platform }}-${{ matrix.vscode_arch }}
          Compress-Archive -Path ..\\vscode-server-${{ matrix.platform }}-${{ matrix.vscode_arch }} -DestinationPath ${{ matrix.artifact }}.${{ matrix.archive }}
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}.${{ matrix.archive }}